services:
  nginx:
      image: nginx:latest
      container_name: nginx
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./conf/nginx.conf:/etc/nginx/nginx.conf
        - ./data/cert:/etc/nginx/ssl
      environment:
        - SERVER_NAME=${SERVER_NAME}

  # databases
  db:
    image: postgres:16
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "1"

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "1"

  # services
  db-migrate:
    container_name: db-migrate
    build: .
    command: python -m scripts.pg_migrate
    depends_on:
      - db

  # microservices
  auth-service:
    container_name: auth
    build: 
      context: .
      dockerfile: Dockerfile
    command: python -m app.microservices.auth.main
    # expose:
    #   - "50051"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - db-migrate
    volumes:
      - ./migrations/auth/versions:/migrations/auth/versions
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "1"

  news-service:
    container_name: news
    build: 
      context: .
      dockerfile: Dockerfile
    command: python -m app.microservices.news.main
    ports:
      - "8001:8000"
    depends_on:
      - mongodb
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "1"

  comments-service:
    container_name: comments
    build: 
      context: .
      dockerfile: Dockerfile
    command: python -m app.microservices.comments.main
    ports:
      - "8002:8000"
    depends_on:
      - mongodb
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "1"

  media-service:
    container_name: media
    build: 
      context: .
      dockerfile: Dockerfile
    command: python -m app.microservices.media.main
    ports:
      - "8003:8000"
    depends_on:
      - db
      - db-migrate
    volumes:
      - ./migrations/media/versions:/migrations/media/versions
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "1"

  matches-service:
    container_name: matches
    build: 
      context: .
      dockerfile: Dockerfile
    command: python -m app.microservices.matches.main
    ports:
      - "8004:8000"
    depends_on:
      - db
      - db-migrate
    volumes:
      - ./migrations/matches/versions:/migrations/matches/versions
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "1"

  users-service:
    container_name: users
    build: 
      context: .
      dockerfile: Dockerfile
    command: python -m app.microservices.users.main
    ports:
      - "8005:8000"
    depends_on:
      - db
      - db-migrate
    volumes:
      - ./migrations/users/versions:/migrations/users/versions
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "1"
