version: "3.8"

services:
  auth-service:
    container_name: auth
    build: 
      context: .
      dockerfile: Dockerfile
    command: python -m app.microservices.auth.main
    # expose:
    #   - "50051"
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./migrations/versions:/migrations/versions
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "1"

  db:
    image: postgres:16
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "1"

