# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: news.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'news.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nnews.proto\x12\x04news\"\r\n\x0bNewsRequest\"\x1f\n\x0cNewsResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2?\n\x0bNewsService\x12\x30\n\x07GetNews\x12\x11.news.NewsRequest\x1a\x12.news.NewsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'news_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NEWSREQUEST']._serialized_start=20
  _globals['_NEWSREQUEST']._serialized_end=33
  _globals['_NEWSRESPONSE']._serialized_start=35
  _globals['_NEWSRESPONSE']._serialized_end=66
  _globals['_NEWSSERVICE']._serialized_start=68
  _globals['_NEWSSERVICE']._serialized_end=131
# @@protoc_insertion_point(module_scope)
